### ISSUE TITLE
module 'enum' has no attribute '__version__'

### ISSUE THREAD

**Issue by bebbo203** [google-research/episodic-curiosity#9]
After following everything on the installation tutorial,
when exectugin "pip install -e ." in episodic-curiosity this error pops out:

`pip install -e .
Obtaining file:///home/bebbo203/Scrivania/Tesi/episodic-curiosity
Requirement already satisfied: DeepMind-Lab in /home/bebbo203/Scrivania/Tesi/episodic_curiosity_env/lib/python3.7/site-packages (from episodic-curiosity==1.0.0) (1.0)
Collecting absl-py>=0.7.0
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Collecting dill>=0.2.9
  Using cached dill-0.3.3-py2.py3-none-any.whl (81 kB)
Collecting enum>=0.4.7
  Using cached enum-0.4.7.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/bebbo203/Scrivania/Tesi/episodic_curiosity_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uw0ybucu/enum/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uw0ybucu/enum/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-uw0ybucu/enum/pip-egg-info
         cwd: /tmp/pip-install-uw0ybucu/enum/
    Complete output (7 lines):
    /home/bebbo203/Scrivania/Tesi/episodic_curiosity_env/lib/python3.7/site-packages/setuptools/version.py:1: UserWarning: Module enum was already imported from /usr/lib/python3.7/enum.py, but /tmp/pip-install-uw0ybucu/enum is being added to sys.path
      import pkg_resources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uw0ybucu/enum/setup.py", line 24, in <module>
        version = main_module.__version__
    AttributeError: module 'enum' has no attribute '__version__'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Then the installation stop. Is there a solution?

**Comment by bebbo203** [comment]
Solved by removing enum from the requirements
